nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
enableGlobalCache: true
enableImmutableInstalls: true

yarnPath: .yarn/releases/yarn-4.9.3.cjs

packageExtensions:
  "@tamagui/vite-plugin@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-native:
        optional: true
  "tamagui@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "tamagui-loader@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-native:
        optional: true
      webpack:
        optional: true
  "babel-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "@react-native-community/datetimepicker@*":
    peerDependenciesMeta:
      expo:
        optional: true
      react-native-windows:
        optional: true
  "react-native-reanimated@*":
    peerDependenciesMeta:
      react-native-worklets:
        optional: true
  "jest-expo@*":
    peerDependenciesMeta:
      jest:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true

logFilters:
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard
  - code: YN0069
    level: discard
