enableGlobalCache: true

enableImmutableInstalls: true

enableInlineBuilds: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@react-native-community/datetimepicker@*":
    peerDependenciesMeta:
      expo:
        optional: true
      react-native-windows:
        optional: true
  "@tamagui/vite-plugin@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-native:
        optional: true
  babel-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  jest-expo@*:
    peerDependenciesMeta:
      jest:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  react-native-reanimated@*:
    peerDependenciesMeta:
      react-native-worklets:
        optional: true
  tamagui-loader@*:
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-native:
        optional: true
      webpack:
        optional: true
  tamagui@*:
    peerDependenciesMeta:
      react-dom:
        optional: true

yarnPath: .yarn/releases/yarn-4.10.3.cjs
