#!/bin/sh

# Check if a package.json file was updated in the merge
if git diff --name-only HEAD@{1} HEAD | grep -q "package.json"; then
  echo "package.json has changed, installing new dependencies..."
  # Use the correct command for your project
  yarn install
fi