name: Supabase Functions Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/supabase-functions.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/supabase-functions.yml'

jobs:
  functions-tests:
    name: Edge Functions Tests
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Setup Node.js for workspace
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Edge Function tests
        run: yarn workspace @my/supabase-functions test:deno

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: functions-test-results
          path: |
            supabase/functions/test-results/
            supabase/functions/coverage/
